theme: jekyll-theme-slate
title: Nitin Tyagi
description: Machine Vision Lab, IITR
<html>
<head>
<style>
img {
  float: right;
}
</style>
</head>
<body>
<p><img src="https://balarsgroup.github.io/Machine%20Vision%20Lab,%20IITR_files/20Nitin.jpg" width="130" height="150" />
</p>

</body>
</html>

