theme: jekyll-theme-slate
title: Nitin Tyagi
description: nitin_t at cs dot iitr dot ac dot in
<html>
<body>

<h1>The img element</h1>

<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">

</body>
</html>
